# Generated by Django 4.2.2 on 2023-08-26 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, default='', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Новый продукт', max_length=255)),
                ('brand', models.CharField(default='', max_length=255)),
                ('size', models.CharField(default='', max_length=15)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('color', models.CharField(default='белый', max_length=20)),
                ('availability_status', models.CharField(default='в наличии', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_special', models.BooleanField(default=True)),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='credo.category')),
                ('subcategory_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credo.subcategory')),
            ],
        ),
    ]
