# Generated by Django 4.2.2 on 2023-08-27 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_status', models.CharField(default='В наличии', max_length=10, verbose_name='Статус наличия')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=255, verbose_name='Бренд')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, default='', max_length=250, null=True, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='', max_length=20, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(default='', max_length=255, null=True, verbose_name='Способ доставки')),
            ],
            options={
                'verbose_name_plural': 'Способ доставки',
            },
        ),
        migrations.CreateModel(
            name='OfficeAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_adress', models.CharField(default='Не выбрано', max_length=255, verbose_name='Адрес пункта выдачи')),
            ],
            options={
                'verbose_name_plural': 'Адрес пункта выдачи',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='На рассмотрении', max_length=50, null=True, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name_plural': 'Статус заказа',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='', max_length=15, verbose_name='Размер')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(default='', max_length=200, verbose_name='Хеш пароля')),
                ('time_register', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name_plural': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='PersonalMeeting',
            fields=[
                ('deliverymethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='credo.deliverymethod')),
                ('meeting_location', models.CharField(max_length=255, verbose_name='Место встречи')),
                ('meeting_date', models.DateTimeField(verbose_name='Дата встречи')),
            ],
            options={
                'verbose_name_plural': 'Личная встреча',
            },
            bases=('credo.deliverymethod',),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(default='', max_length=255, null=True, unique=True, verbose_name='Подкатегория')),
                ('category_name', models.ForeignKey(blank=True, default='', max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='credo.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Подкатегория',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=255, verbose_name='Имя товара')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('is_special', models.BooleanField(default=True, verbose_name='Является рекламной')),
                ('availability_status', models.ForeignKey(default='', max_length=10, on_delete=django.db.models.deletion.PROTECT, to='credo.availabilitystatus', verbose_name='Статус наличия')),
                ('brand', models.ForeignKey(default='', max_length=255, on_delete=django.db.models.deletion.PROTECT, to='credo.brand', verbose_name='Бренд')),
                ('color', models.ForeignKey(default='', max_length=20, on_delete=django.db.models.deletion.PROTECT, to='credo.color', verbose_name='Цвет')),
                ('size', models.ForeignKey(default='', max_length=15, on_delete=django.db.models.deletion.PROTECT, to='credo.size', verbose_name='Размер')),
                ('subcategory_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='credo.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name_plural': 'Товар',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, default=1, max_digits=50, verbose_name='Количество')),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата оформления заказа')),
                ('comment', models.CharField(default='', max_length=400, null=True, verbose_name='Комментарий')),
                ('delivery_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='credo.deliverymethod', verbose_name='Способ доставки')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='credo.product', verbose_name='Товар')),
                ('status', models.ForeignKey(default='На рассмотрении', null=True, on_delete=django.db.models.deletion.CASCADE, to='credo.orderstatus', verbose_name='Статус заказа')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='credo.user', verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name_plural': 'Заказ',
            },
        ),
        migrations.CreateModel(
            name='EuroPost',
            fields=[
                ('deliverymethod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='credo.deliverymethod')),
                ('tracking_number', models.CharField(max_length=50, verbose_name='Номер отслеживания')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('lastname', models.CharField(default='', max_length=50, verbose_name='Отчество')),
                ('phone_number', models.CharField(default='+375', max_length=15, verbose_name='Номер телефона')),
                ('office_adress', models.ForeignKey(default='Не выбрано', on_delete=django.db.models.deletion.CASCADE, to='credo.officeadress', verbose_name='Адрес пункта выдачи')),
            ],
            options={
                'verbose_name_plural': 'Европочта',
            },
            bases=('credo.deliverymethod',),
        ),
    ]
