# Generated by Django 4.2.2 on 2023-08-26 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='availability_status',
            field=models.CharField(default='в наличии', max_length=10, verbose_name='Статус наличия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=255, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='credo.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(default='белый', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_special',
            field=models.BooleanField(default=True, verbose_name='Является рекламной'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='Новый продукт', max_length=255, verbose_name='Имя товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='', max_length=15, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credo.subcategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=200, verbose_name='Хеш пароля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=25, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
