# Generated by Django 4.2.2 on 2023-08-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilitystatus',
            options={'verbose_name_plural': 'Статус наличия'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Бренд'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'Цвет'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': 'Размер'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Картинка'),
        ),
    ]
