# Generated by Django 4.2.2 on 2023-09-07 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credo', '0002_alter_availabilitystatus_options_alter_brand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Пользователи'},
        ),
    ]
